//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlLab.nxslt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NXsltStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NXsltStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlLab.nxslt.NXsltStrings", typeof(NXsltStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified credentials &apos;{0}&apos; don&apos;t match username:password@domain pattern..
        /// </summary>
        internal static string ErrorBadCredentials {
            get {
                return ResourceManager.GetString("ErrorBadCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -af and -an options cannot be used simultaneously..
        /// </summary>
        internal static string ErrorBothAssemblyFileNameAndName {
            get {
                return ResourceManager.GetString("ErrorBothAssemblyFileNameAndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;-pi&apos; and &apos;-xs&apos; options are mutually exclusive..
        /// </summary>
        internal static string ErrorBothNoSourceAndPI {
            get {
                return ResourceManager.GetString("ErrorBothNoSourceAndPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;-xs&apos; option and source document filename (or &apos;-&apos;) are mutually exclusive..
        /// </summary>
        internal static string ErrorBothNoSourceAndSource {
            get {
                return ResourceManager.GetString("ErrorBothNoSourceAndSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input and the stylesheet document cannot both be read from stdin. At least one of them must be loaded from a URL..
        /// </summary>
        internal static string ErrorBothStdin {
            get {
                return ResourceManager.GetString("ErrorBothStdin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;-pi&apos; option cannot be used when the stylesheet argument is specified..
        /// </summary>
        internal static string ErrorBothStylesheetAndPI {
            get {
                return ResourceManager.GetString("ErrorBothStylesheetAndPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing command line..
        /// </summary>
        internal static string ErrorCommandLineParsing {
            get {
                return ResourceManager.GetString("ErrorCommandLineParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while compiling stylesheet &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorCompileStyle {
            get {
                return ResourceManager.GetString("ErrorCompileStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while instantiating &apos;{0}&apos; type: {1}.
        /// </summary>
        internal static string ErrorCreateResolver {
            get {
                return ResourceManager.GetString("ErrorCreateResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating file &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorCreatingFile {
            get {
                return ResourceManager.GetString("ErrorCreatingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate credentials..
        /// </summary>
        internal static string ErrorDuplicateCredentials {
            get {
                return ResourceManager.GetString("ErrorDuplicateCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two extension objects cannot be bound to &apos;{0}&apos; namespace URI..
        /// </summary>
        internal static string ErrorExtNamespaceClash {
            get {
                return ResourceManager.GetString("ErrorExtNamespaceClash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension object &apos;{0}&apos; must be bound to a namespace URI..
        /// </summary>
        internal static string ErrorExtNoNamespace {
            get {
                return ResourceManager.GetString("ErrorExtNoNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; not found..
        /// </summary>
        internal static string ErrorGetType {
            get {
                return ResourceManager.GetString("ErrorGetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; not found in &apos;{1}&apos; assembly..
        /// </summary>
        internal static string ErrorGetTypeFromAssembly {
            get {
                return ResourceManager.GetString("ErrorGetTypeFromAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source document does not contain an &apos;xml-stylesheet&apos; processing instruction of this form: &lt;?xml-stylesheet type=&apos;text/xsl&apos; href=&apos;stylesheet-url&apos;?&gt;.
        /// </summary>
        internal static string ErrorInvalidPI {
            get {
                return ResourceManager.GetString("ErrorInvalidPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading assembly &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorLoadAssembly {
            get {
                return ResourceManager.GetString("ErrorLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading specified EXSLT.NET assembly &apos;{0}&apos;. Error details: {1}.
        /// </summary>
        internal static string ErrorLoadExsltLibNotFound {
            get {
                return ResourceManager.GetString("ErrorLoadExsltLibNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GotDotNet.Exslt.ExsltTransform class from specified EXSLT.NET assembly &apos;{0}&apos; cannot be instantiated. Error details: {1}.
        /// </summary>
        internal static string ErrorLoadExsltTransformTypeCannotBeInstantiated {
            get {
                return ResourceManager.GetString("ErrorLoadExsltTransformTypeCannotBeInstantiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified EXSLT.NET assembly &apos;{0}&apos; doesn&apos;t contain GotDotNet.Exslt.ExsltTransform class. Error details: {1}.
        /// </summary>
        internal static string ErrorLoadExsltTransformTypeNotFound {
            get {
                return ResourceManager.GetString("ErrorLoadExsltTransformTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing assembly file name after &apos;-af&apos; option..
        /// </summary>
        internal static string ErrorMissingAssemblyFileName {
            get {
                return ResourceManager.GetString("ErrorMissingAssemblyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing assembly name after &apos;-an&apos; option..
        /// </summary>
        internal static string ErrorMissingAssemblyName {
            get {
                return ResourceManager.GetString("ErrorMissingAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing EXSLT.NET assembly file path after &apos;-exslt&apos; option..
        /// </summary>
        internal static string ErrorMissingExsltLibPath {
            get {
                return ResourceManager.GetString("ErrorMissingExsltLibPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing list of extension class names after &apos;-ext&apos; option..
        /// </summary>
        internal static string ErrorMissingExtClassNames {
            get {
                return ResourceManager.GetString("ErrorMissingExtClassNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;=&apos; character must be preceded by the name of a parameter or a namespace declaration..
        /// </summary>
        internal static string ErrorMissingName {
            get {
                return ResourceManager.GetString("ErrorMissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing output filename after &apos;-o&apos; option..
        /// </summary>
        internal static string ErrorMissingOutFileName {
            get {
                return ResourceManager.GetString("ErrorMissingOutFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing URI resolver type name after &apos;-r&apos; option..
        /// </summary>
        internal static string ErrorMissingResolverTypeName {
            get {
                return ResourceManager.GetString("ErrorMissingResolverTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing source filename..
        /// </summary>
        internal static string ErrorMissingSource {
            get {
                return ResourceManager.GetString("ErrorMissingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing stylesheet filename..
        /// </summary>
        internal static string ErrorMissingStylesheet {
            get {
                return ResourceManager.GetString("ErrorMissingStylesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace declaration &apos;{0}&apos; is missing a URI following the &apos;=&apos; character..
        /// </summary>
        internal static string ErrorMissingURI {
            get {
                return ResourceManager.GetString("ErrorMissingURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is missing a value following the &apos;=&apos; character..
        /// </summary>
        internal static string ErrorMissingValue {
            get {
                return ResourceManager.GetString("ErrorMissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing credentials after &apos;-xmlc&apos; option..
        /// </summary>
        internal static string ErrorMissingXMLCredentials {
            get {
                return ResourceManager.GetString("ErrorMissingXMLCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing credentials after &apos;-xslc&apos; option..
        /// </summary>
        internal static string ErrorMissingXSLTCredentials {
            get {
                return ResourceManager.GetString("ErrorMissingXSLTCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing document: {0}: {1}.
        /// </summary>
        internal static string ErrorParsingDoc {
            get {
                return ResourceManager.GetString("ErrorParsingDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylesheet &apos;{0}&apos;, defined in &apos;xml-stylesheet&apos; processing instruction not found..
        /// </summary>
        internal static string ErrorPIStylesheetNotFound {
            get {
                return ResourceManager.GetString("ErrorPIStylesheetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stylesheet (in file name, &apos;-&apos; or &apos;-pi&apos; ways) should be specified along with &apos;-pp&apos; option..
        /// </summary>
        internal static string ErrorStylesheetAndPrettyPrintMode {
            get {
                return ResourceManager.GetString("ErrorStylesheetAndPrettyPrintMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while executing transformation: {0}.
        /// </summary>
        internal static string ErrorTransform {
            get {
                return ResourceManager.GetString("ErrorTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified URI resolver type &apos;{0}&apos; is not XmlResolver type..
        /// </summary>
        internal static string ErrorTypeNotXmlResolver {
            get {
                return ResourceManager.GetString("ErrorTypeNotXmlResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix &apos;{0}&apos; cannot be resolved.  Use xmlns:{0}=&apos;...&apos; to bind &apos;{0}&apos; to a URI..
        /// </summary>
        internal static string ErrorUnboundedPrefix {
            get {
                return ResourceManager.GetString("ErrorUnboundedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized option : &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorUnrecognizedOption {
            get {
                return ResourceManager.GetString("ErrorUnrecognizedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name &apos;{0}&apos; must be followed by an &apos;=&apos; character..
        /// </summary>
        internal static string ErrorWrongParam {
            get {
                return ResourceManager.GetString("ErrorWrongParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;from stdin&gt;.
        /// </summary>
        internal static string FromStdin {
            get {
                return ResourceManager.GetString("FromStdin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:transform xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;  		
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;xsl:copy-of select=&quot;.&quot;/&gt;      
        ///  &lt;/xsl:template&gt;
        ///&lt;/xsl:transform&gt;.
        /// </summary>
        internal static string IdentityTransformation {
            get {
                return ResourceManager.GetString("IdentityTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;username&gt;\w+):?(?&lt;psw&gt;\w*)@?(?&lt;domain&gt;\w*).
        /// </summary>
        internal static string PatternCredentials {
            get {
                return ResourceManager.GetString("PatternCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylesheet load/compile time:  {0, 9:f3} milliseconds
        ///Transformation time:           {1, 9:f3} milliseconds
        ///Total execution time:          {2, 9:f3} milliseconds
        ///.
        /// </summary>
        internal static string Timings {
            get {
                return ResourceManager.GetString("Timings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: nxslt source stylesheet [options] [param=value...] [xmlns:prefix=uri...]
        ///		
        ///Options:
        ///  -?            Show this message
        ///  -o filename   Write output to named file    
        ///  -xw           Strip non-significant whitespace from source and stylesheet
        ///  -xe           Do not resolve external definitions during parse phase
        ///  -xi           Do not process XInclude during parse phase
        ///  -v            Validate documents during parse phase    
        ///  -t            Show load and transformation timings
        ///  -xs        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UsageBody {
            get {
                return ResourceManager.GetString("UsageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET 2.0 XSLT command line utility, version {0}.{1}.{2}
        ///(c) 2004-2005 Oleg Tkachenko, http://www.xmllab.net
        ///Running under .NET {3}.{4}.{5}.{6}.
        /// </summary>
        internal static string UsageHeader {
            get {
                return ResourceManager.GetString("UsageHeader", resourceCulture);
            }
        }
    }
}
